jenkins:
  build: jenkins
  hostname:  jenkins
  container_name:    jenkins
  ports:
    - "8080:8080"
    - "50000:50000"
  tty: true
  privileged: true
  volumes:
    # Just specify a path and let the Engine create a volume
    #- /Users/juan/workspace/jenkins_scripts:/opt/millicominfra:rw

rundeck:
  build: rundeck
  hostname:  rundeck
  container_name:    rundeck
  ports:
    - "4440:4440"
  environment:
    SERVER_URL: http://192.168.99.100:4440
  tty: true
  privileged: true
  #links:
  #        - node1


ubuntu:
  build: ubuntu
  hostname:  ubuntu16
  container_name:    ubuntu16
  tty: true
  privileged: true


