jenkins:
  build: jenkins
  hostname:  jenkins
  container_name:    jenkins
  ports:
    - "8080:8080"
    - "50000:50000"
  tty: true
  privileged: true
  links:
      - ubuntu
  #volumes:
    # Just specify a path and let the Engine create a volume
    #- /Users/juan/workspace/jenkins_scripts:/opt/millicominfra:rw



ubuntu:
  build: ubuntu
  hostname:  ubuntu16
  container_name:    ubuntu16
  tty: true
  privileged: true



